var TILE_TYPE_SAND = 1;
var TILE_TYPE_ROCK = 2;
var TILE_TYPE_SPICE = 3;
var TILE_TYPE_RICH_SPICE = 4;

var UNIT_TYPE_BATTLE_TANK = 1;
var UNIT_TYPE_SIEGE_TANK = 2;
var UNIT_TYPE_LAUNCHER = 3;
var UNIT_TYPE_DEVASTATOR = 4;
var UNIT_TYPE_HARVESTER = 5;
var UNIT_TYPE_JEEP = 6;
var UNIT_TYPE_TRIKE = 7;
var UNIT_TYPE_SONIC_TANK = 8;
var UNIT_TYPE_DEVIATOR = 9;
var UNIT_TYPE_MCV = 10;

var BUILDING_TYPE_SILO = 1;
var BUILDING_TYPE_POWERPLANT = 2;
var BUILDING_TYPE_REPAIRSHOP = 3;
var BUILDING_TYPE_BARRACKS = 4;
var BUILDING_TYPE_RADAR = 5;
var BUILDING_TYPE_LIGHTFACTORY = 6;
var BUILDING_TYPE_CONSTRUCTION_YARD = 7;
var BUILDING_TYPE_FACTORY = 8;
var BUILDING_TYPE_AIRBASE = 9;
var BUILDING_TYPE_TURRET = 10;
var BUILDING_TYPE_CONCRETE = 11;
var BUILDING_TYPE_REFINERY = 12;
var BUILDING_TYPE_ROCKET_TURRET = 13;
var BUILDING_TYPE_WALL = 14;

var VIEW_DIRECTION_TOPLEFT = 1;
var VIEW_DIRECTION_TOP = 2;
var VIEW_DIRECTION_TOPRIGHT = 3;
var VIEW_DIRECTION_RIGHT = 4;
var VIEW_DIRECTION_BOTTOMRIGHT = 5;
var VIEW_DIRECTION_BOTTOM = 6;
var VIEW_DIRECTION_BOTTOMLEFT = 7;
var VIEW_DIRECTION_LEFT = 8;


var BUY_OPTION_DEVASTATOR = 1;
var BUY_OPTION_SIEGE_TANK = 2;
var BUY_OPTION_TANK = 3;
var BUY_OPTION_LAUNCHER = 4;

var BUY_OPTION_POWERPLANT = 5;
var BUY_OPTION_HARVESTER = 6;
var BUY_OPTION_RADAR = 7;
var BUY_OPTION_CONCRETE = 8;
var BUY_OPTION_JEEP = 9;
var BUY_OPTION_DEVIATOR = 10;
var BUY_OPTION_REFINERY = 11;
var BUY_OPTION_FACTORY = 12;
var BUY_OPTION_ROCKET_TURRET = 13;
var BUY_OPTION_SILO = 14;
var BUY_OPTION_REPAIR_DEPO  = 15;
var BUY_OPTION_AIRBASE = 16;
var BUY_OPTION_WALL = 17;
var BUY_OPTION_MCV = 18;
var BUY_OPTION_TURRET = 19;
var BUY_OPTION_SONIC_TANK = 20;
var BUY_OPTION_TRIKE = 21;

var EXPLOSION_TYPE_BIG = 1;
